version: '3'

services:
  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/ubuntu/jenkins_home/workspace/gitlab_ci/frontend/build:/usr/share/nginx/html
      - /home/ubuntu/static/:/usr/share/nginx/static/
